[package]
name = "silver_gl"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
memoffset = "0.8.0"
rand = "0.8.5"

[build-dependencies]
gl_generator = "0.14.0"