[package]
name = "silver_gl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
image = "0.24.3"
cgmath = "0.18.0"
tobj = "3.2.3"
memoffset = "0.8.0"
rand = "0.8.5"